models.py
# -*- coding: utf-8 -*-
import os
from django.db import models
from django.db.models import Q
from image_cropping import ImageRatioField

class Categoria(models.Model):
    nome = models.CharField(max_length=20)
    nome_en = models.CharField(max_length=20,verbose_name=u"nome em inglês")
    info = models.TextField(help_text=u'informações sobre as suites desse tipo')
    info_en = models.TextField(verbose_name=u"info em inglês",help_text=u'informações sobre as suites desse tipo')
    preco = models.DecimalField(max_digits=8, decimal_places=2,help_text=u'preços da diarias para as suites deste tipo')
    ordem = models.IntegerField(default=1,null=True,blank=True)
    
    class Meta:
        verbose_name = u"tipo de suíte"		
        verbose_name_plural = u"tipos de suítes"		
        ordering = ('ordem',)

    def __unicode__(self):
        return u"%s" % self.nome


class Evento(models.Model): 
    titulo = models.CharField(max_length=50)
    resumo = models.CharField(max_length=100,default=" ",null=True,blank=True)
    descricao = models.TextField()
    descricao_en = models.TextField(verbose_name=u"descrição em inglês")

    categoria = models.ForeignKey(Categoria,null=True,blank=False)
    
    data = models.DateTimeField(verbose_name="data",null=True,blank=True)
    foto_principal = models.ImageField(upload_to=u"eventos/", help_text=u"imagem principal. Exemplo de proporção: 757px X 563px")
    cropping = ImageRatioField(u'foto_principal', '757x563')
    ordem = models.IntegerField(null=True)
    
    class Meta:
        verbose_name = u"suíte"
        ordering = ('ordem',)


    def __unicode__(self):
        return u"%s" % self.titulo

    def get_fotos(self):
        return self.foto_set.all()
    
class Foto(models.Model):
    evento = models.ForeignKey(Evento)
    legenda = models.CharField(max_length=150,null=True, blank=True)
    foto = models.ImageField(upload_to=u"eventos/%Y/%m/%d/" )
    cropping = ImageRatioField('foto', '400x300',free_crop=True)
    
    def __unicode__(self):
        
        return u"%s - %s" % (self.evento.titulo,os.path.basename( self.foto.name))



# vim: set ts=4 sw=4 sts=4 expandtab:

views.py
from django.http import HttpResponseRedirect
from django import forms
from django.shortcuts import render
from django.views.generic import View,DetailView
from django.conf import settings
from django.core.files import File
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage

import tempfile
import os
import zipfile
import shutil

from appfotos.models import Evento, Foto

class UploadFotoForm(forms.Form):
    ids = forms.CharField(max_length=50)
    file  = forms.FileField()
   
class FotoUploadView(View):
    def get(self, request):
        form = UploadFotoForm(initial={'ids':request.GET.get('ids')})
        form.fields['ids'].widget = forms.HiddenInput()
        response = render(request,'eventos/foto_upload.html',{'form':form})
        return response

    def post(self,request):
        form = UploadFotoForm(request.POST, request.FILES)
        if form.is_valid():
            self.handle_uploaded_file(request.FILES['file'],form)
        return HttpResponseRedirect('/admin/eventos/evento/')

    def handle_uploaded_file(self,f,form):
        ids = form.cleaned_data['ids'].split(',')
        pasta_temp = tempfile.mkdtemp()
        file_temp = os.path.join(pasta_temp,ids[0]+".zip")

        with open(file_temp, 'wb+') as destination:
            for chunk in f.chunks():
                destination.write(chunk)
       
        # criando pasta temporaria para salvar os unzip
        unzip_pasta = os.path.join(pasta_temp,"unzip")
        if not os.path.exists(unzip_pasta):
            os.makedirs(unzip_pasta)
        unzip(file_temp,unzip_pasta)

        # salvando novos arquivos usando a pasta temporaria
        evento = Evento.objects.get(id=ids[0])
        for name in os.listdir(unzip_pasta):
            fi = os.path.join(unzip_pasta,name)
            if os.path.isfile(fi):
                with open(fi) as foto_file:
                    foto = Foto(evento=evento,foto=File(foto_file))
                    foto.save()
        #shutil.rmtree(unzip_pasta)

class EventosView(View):
    def get(Self,request):
        eventos = Evento.objects.da_unidade(request)
        paginator = Paginator(eventos,18)
        page = request.GET.get('page')
        try:
            eventos = paginator.page(page)
        except PageNotAnInteger:
            # If page is not an integer, deliver first page.
            eventos = paginator.page(1)
        except EmptyPage:
            # If page is out of range (e.g. 9999), deliver last page of results.
            eventos = paginator.page(paginator.num_pages)

        categorias = {}
        for e in eventos:
            if e.categoria:
                categorias[e.categoria.id]=e.categoria

        return render(request,'eventos/eventos.html',{'eventos':eventos,'categorias':categorias})

class EventoView(DetailView):
    model = Evento
    template_name= "eventos/evento.html" 

def unzip(zipFilePath, destDir):
    #os.system('cd %s; unzip -f %s' % (destDir,zipFilePath))
    zfile = zipfile.ZipFile(zipFilePath)
    zfile.extractall(destDir)

templates/eventos/ciclo-eventos.html
{% load staticfiles %}

    <h2 class="secao"><a href="/eventos/"><span>Eventos</span></a></h2>
    <p class="setas">
        <a href="#" data-cycle-context="#eventos-slide" data-cycle-cmd="prev" class="evprev prev"><prev</a>
        <a href="#" data-cycle-context="#eventos-slide" data-cycle-cmd="next" class="evnext next">next</a>
    </p>
{% load thumbnail %}
<div class="ciclo-eventos">
    <ul id='eventos-carousel'>
         {% for ev in eventos %}
         <li><div class='evento'>
                       <a href="{% url 'evento' ev.id %}">{% thumbnail ev.foto_principal "127x86" as im %}<img alt="{{ ev.categoria }}"  src="{{im.url}}" width="127px" height="86px" >{% endthumbnail %}
            <h3>{{ ev.titulo }}</h3>
             <p>{{ ev.resumo }}</p>
             </a></div>
        </li>
         {% endfor %}
    </ul>
</div>
<div class="clear">&nbsp;</div>

templates/eventos/evento.html
{% extends "pagina-interna.html" %}
{% load static %}
{% block title %}{{ block.super }} | Evento {% endblock %}
{% block tituloheader %}<a href="{% url 'eventos' %}">Eventos</a> | {{ object.titulo }}{% endblock %}

{% block classbody %}pg-evento{% endblock %}
{% block conteudointerno %}
<p>{{ object.resumo }}</p>
<p>{{ object.descricao }}</p>
        <h3 class="header">Fotos </h3>
<p style="text-align: center">
{% load thumbnail %}
{% for f in  object.foto_set.all %}
    {% thumbnail f.foto "800x600" as big %} 
    {% thumbnail f.foto "100x100" crop="center" as small %} 
    <a href="{{ big.url }}" class="galeria"><img heigth="100px" src="{{ small.url }}"></a>
    {% endthumbnail %}
    {% endthumbnail %}
{% endfor %}
</p>

<!--<p class="link" style="text-align:center"><a href="/eventos/">Outros Eventos</a></p> -->


{% endblock %}

templates/eventos/eventos.html
{% extends "pagina-interna.html" %}
{% load static %}
{% block title %}{{ block.super }} | Eventos {% endblock %}
{% block tituloheader %}Eventos{% endblock %}

{% block conteudointerno %}
<div id="filters">
  <a href="#selected" class='selected' data-filter="*">todos</a>
  {% for k, c in categorias.items %}
    <a href="#cat{{ c.id }}" data-filter=".cat{{ c.id}}">{{ c.nome }}</a>
  {% endfor %}
  <a href="#cat" data-filter=".cat">outros</a>
  
  <div class="clear"> </div>
</div>

  <div class="clear"> </div>
<div id='eventos-iso'>
{% load thumbnail %}
    {% for ev in eventos %}
    <div class='item cat{{ ev.categoria.id }}'>

        <a href="{% url 'evento' ev.id %}">{% thumbnail ev.foto_principal "170x100" as im %}<img alt="{{ ev.categoria }}"  src="{{im.url}}" width="127px" height="86px" >{% endthumbnail %}</a>
        <h3>{{ ev.titulo }}</h3>
        <p>{{ ev.data|date:"j \d\e F \d\e Y"}}</p>       
    </div>
    {% endfor %}
  </div>


<div class="outer">
<div id="pagination">
    {% if eventos.has_previous %}
            <a class='prev' href="?page={{ eventos.previous_page_number }}">prev</a>
    {% endif %}

    {% for p in eventos.paginator.page_range %}
        {% if eventos.number == p %}
            <span class='current'>{{eventos.number}}</span>
        {% else %}
            <a href="?page={{ p }}">{{ p }}</a>
        {% endif %}
    {% endfor %}

    {% if eventos.has_next %}
        <a class='next' href="?page={{ eventos.next_page_number }}">next</a>
    {% endif %}
</div>
</div>
{% endblock %}

templates/eventos/foto_upload.html
{% extends "admin/change_form.html" %}
{% block breadcrumbs %}
<div class="breadcrumbs">
    <a href="{% url 'admin:index' %}">Início</a>
&rsaquo; <a href="/admin/eventos/">Eventos</a>
&rsaquo; <a href="/admin/eventos/evento/">Eventos</a>
&rsaquo; Enviar zip de fotos 
</div>
{% endblock %}
{% block content %}

<form method="POST" enctype="multipart/form-data" action=".">
<div>
{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Enviar" >
</div>
</form>
{% endblock %}

templates/eventos/tipos-suites.html
{% load staticfiles %}
{% load i18n %}{% get_available_languages as LANGUAGES %}
{% get_current_language as LANGUAGE_CODE %}
{% load thumbnail %}

    {% ifequal LANGUAGES.0.0 LANGUAGE_CODE %}
         {% for tipo in tipos %}
    <h2>{{ tipo.nome }}</h2>
        <div>
           <p>{{ tipo.info }}</p>
            <p class="green">Conheça tudo sobre nossas {{ tipo.nome|lower}}!<br />
		{% for suite in tipo.evento_set.all %}
		
		{% if forloop.last %}
		 e  
                <a href="/suites/?suite=s{{ suite.id}}">{{ suite.titulo }}</a>
		{% else %}
                <a href="/suites/?suite=s{{ suite.id}}">{{ suite.titulo }}</a>{% ifequal forloop.revcounter 2 %}{% else %},{% endifequal %}
		{% endif %}
		{% endfor %}
            </p>
            <p class="tarifa">Tarifa/dia: R$ <span class="preco">{{ tipo.preco }}</span></p>
            <p class="clear"></p>
    </div>
       {% endfor %}
    {% else %}
         {% for tipo in tipos %}
    <h2>{{ tipo.nome_en }}</h2>
        <div>
           <p>{{ tipo.info_en }}</p>
            <p class="green">Check all about our {{ tipo.nome_en|lower }}!<br />
		{% for suite in tipo.evento_set.all %}
		
		{% if forloop.last %}
		 e  
                <a href="/suites/?suite=s{{ suite.id}}">{{ suite.titulo }}</a>
		{% else %}
                <a href="/suites/?suite=s{{ suite.id}}">{{ suite.titulo }}</a>{% ifequal forloop.revcounter 2 %}{% else %},{% endifequal %}
		{% endif %}
		{% endfor %}
            </p>
            <p class="tarifa">Tarifa/dia: R$ <span class="preco">{{ tipo.preco }}</span></p>
            <p class="clear"></p>
    </div>
       {% endfor %}
{% endifequal %}